### ISSUE TITLE
systemvm_template.rb attributes case without else

### ISSUE THREAD

**Issue by imduffy15** [cloudops/cookbook_cloudstack#3]
The systemvm_template.rb attributes file covers 4.4, 4.3, 4.2 using a case, when, when, when.... statement. It should provide some reasonable default or throw an exception when the version isn't 4.4, 4.3 or 4.2.

**Comment by pdion891** [comment]
If the systemvm template is not define, it will take the one configure into the database.
I'll add a comment in the attributes file for clarification.
