### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by imduffy15** [cloudops/cookbook_cloudstack#4]
I know chef convention says we should place cookbook name, recipe, author, copyright at the top of each file but I think its a bit messy for projects that may have a bunch of different authors.

For example, the kvm_agent.rb file says author Pierre-luc-dion but copyright roeland kuipers.

Could we just standardise all headers to just be the apache license?

**Comment by pdion891** [comment]
normalized license header..

Thanks for the notice!
