### ISSUE TITLE
Cookbooks not updated on supermaket.chef.io

### ISSUE THREAD

**Issue by salsa-dev** [cloudops/cookbook_cloudstack#5]
Dear devs!

Thanks for all your great work!

Why are the cloudstack cookbooks not updated on Chef Supermarket ?
https://supermarket.chef.io/cookbooks/cloudstack
https://supermarket.chef.io/cookbooks/cloudstack_wrapper

**Comment by pdion891** [comment]
you are right, we will update the supermarket version of both cookbooks.

Thanks for the reminder!

**Comment by pdion891** [comment]
Latest cookbooks are now on the supermarket! 

Cheers,
